GET https://forex.1forge.com/1.0.3/quotes?pairs=EURUSD,GBPJPY,AUDUSD&api_key=bfBuXo30skEAA0ES4Wz3lNQksUjcTuce

GET https://forex.1forge.com/1.0.3/quota?api_key=bfBuXo30skEAA0ES4Wz3lNQksUjcTuce

GET https://forex.1forge.com/1.0.3/symbols?api_key=bfBuXo30skEAA0ES4Wz3lNQksUjcTuce 

google-chrome --remote-debugging-port=9222

Get http://localhost:3000/orderBooks/all

Get http://localhost:3000/sever-tcp/start-server
Get http://localhost:3000/sever-tcp/stop-server

Get https://api.coinmarketcap.com/v2/ticker/2546/

Get http://localhost:3000/sever-tcp/user-balance
Get http://localhost:3000/orderBooks/order-books/3

Get http://localhost:3000/orderBooks/order-books/?startDate=1530738000000&endDate=1530910800000

Get https://testnet.gateway.proximax.io/node/info

Get https://mijinnet.gateway.proximax.io/node/info

Get https://testnet3.gateway.proximax.io/node/info

Get https://mainnet.gateway.proximax.io/node/info
Get https://dev.gateway.proximax.io/node/info

Get http://localhost:3000/orders/all
Get http://localhost:3000/orders/find/?startDate=1530738000000&endDate=1530910800000
Get http://localhost:3000/trades/find/?startDate=1531147708186&endDate=1531147708207
Get http://localhost:3000/trades/all
POST http://localhost:3000/orderBooks/create HTTP/1.1
content-type: application/json

{ 
   "exchangeName": "bitfinex",
    "pair": "BTC-GDP",
    "bid": 6201.56,
    "ask": 6215.15,
    "time": "1530262758920"
}

POST http://localhost:3000/orders/save HTTP/1.1
content-type: application/json

{ 
   "exchange": "bitfinex",
    "pair": "BTC-GDP",
    "price": 6200.56,
    "volume": 1,
    "typeOrder": "buy", 
    "fee": 0.2,
    "arbitrageId": "euifuihfio",
    "deviationPrice": 0.05, 
    "time": "1530738000001"
}