GET https://forex.1forge.com/1.0.3/quotes?pairs=EURUSD,GBPJPY,AUDUSD&api_key=bfBuXo30skEAA0ES4Wz3lNQksUjcTuce

GET https://forex.1forge.com/1.0.3/quota?api_key=bfBuXo30skEAA0ES4Wz3lNQksUjcTuce

GET https://forex.1forge.com/1.0.3/symbols?api_key=bfBuXo30skEAA0ES4Wz3lNQksUjcTuce






POST http://localhost:3000/orderBooks/create HTTP/1.1
content-type: application/json

{ 
   "exchangeName": "bittrex",
    "pair": "BTC-USDT",
    "bid": 6201.56,
    "ask": 6215.15,
    "time": "1530262753920"
}

Get http://localhost:3000/orderBooks/all
